# main text of home
name: Alex Ahmed
bio: A Girl who travels the world eating noodles

# twitter summary info
description: A blog about technology and stuff related

picture: assets/images/picture.jpg

url: https://ozzmotic.github.io/me
# your url: http://USERNAME.github.io

# if you don't have any of social below, comment the line
# facebook: myfacebook
twitter: WomensFormula
github: ozzmotic
email: ahmed.al@husky.neu.edu

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
